#!/bin/bash

# Install and configure Coturn STUN/TURN server for WebRTC

set -e

if [ "$EUID" -ne 0 ]; then
    echo "❌ Please run as root: sudo $0"
    exit 1
fi

echo "🔧 Installing Coturn STUN/TURN server..."
echo ""

# Install coturn
apt-get update
apt-get install -y coturn

# Enable coturn service
sed -i 's/#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn

# Backup original config
cp /etc/turnserver.conf /etc/turnserver.conf.backup

# Generate random secret for TURN authentication
TURN_SECRET=$(openssl rand -hex 32)

# Create turnserver config
cat > /etc/turnserver.conf << EOF
# STUN/TURN server for BeamCam WebRTC

# Listen on all interfaces
listening-ip=0.0.0.0

# External IP (public IP of your server)
# Auto-detect or set manually: external-ip=YOUR.PUBLIC.IP
external-ip=$(curl -s ifconfig.me)

# STUN/TURN ports
listening-port=3478
tls-listening-port=5349

# Relay IP
relay-ip=0.0.0.0

# Use fingerprints
fingerprint

# Use long-term credentials
lt-cred-mech
use-auth-secret
static-auth-secret=$TURN_SECRET

# Server name (your domain)
server-name=beamcam.live
realm=beamcam.live

# Total quota (10 MB per session)
total-quota=100
bps-capacity=0

# No multicast
no-multicast-peers

# Logging
verbose
log-file=/var/log/turnserver.log

# Deny private IP ranges as relay endpoints
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=172.16.0.0-172.31.255.255

# Allow only specific ports for relay
min-port=49152
max-port=65535

# Security
no-cli
no-loopback-peers
no-multicast-peers

# TLS (optional - certificates needed)
# cert=/etc/letsencrypt/live/beamcam.live/fullchain.pem
# pkey=/etc/letsencrypt/live/beamcam.live/privkey.pem
EOF

echo ""
echo "✅ Coturn installed and configured!"
echo ""
echo "📝 Configuration:"
echo "   Config: /etc/turnserver.conf"
echo "   Secret: $TURN_SECRET"
echo "   External IP: $(curl -s ifconfig.me)"
echo ""
echo "🔐 TURN credentials for client:"
echo "   Username: (timestamp-based, generated by client)"
echo "   Secret: $TURN_SECRET"
echo ""
echo "📂 Save this to ./.turn-secret:"
echo "$TURN_SECRET" > ./.turn-secret
chmod 600 ./.turn-secret
echo "   ✓ Saved to .turn-secret"
echo ""
echo "🔥 Firewall rules needed:"
echo "   sudo ufw allow 3478/tcp"
echo "   sudo ufw allow 3478/udp"
echo "   sudo ufw allow 5349/tcp"
echo "   sudo ufw allow 49152:65535/tcp"
echo "   sudo ufw allow 49152:65535/udp"
echo ""
echo "▶️  Start coturn:"
echo "   sudo systemctl start coturn"
echo "   sudo systemctl enable coturn"
echo ""
echo "📊 Test STUN server:"
echo "   stunclient $(curl -s ifconfig.me) 3478"
echo ""
